SSO/MiddlewareIdentityProvider/Pages/About.cshtml.cs
using ComponentSpace.Saml2.Utility;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MiddlewareIdentityProvider.Pages
{
    public class AboutModel : PageModel
    {
        public AboutModel(ILicense license)
        {
            string licenseType;

            if (license.IsLicensed)
            {
                licenseType = "Licensed";
            }
            else
            {
                licenseType = $"Evaluation (Expires {license.Expires.ToShortDateString()})";
            }

            ProductInformation = $"ComponentSpace.Saml2, Version={license.Version}, {licenseType}";
        }

        public string ProductInformation { get; set; }

        public void OnGet()
        {

        }
    }
}

SSO/MiddlewareIdentityProvider/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MiddlewareIdentityProvider.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SSO/MiddlewareIdentityProvider/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MiddlewareIdentityProvider.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SSO/MiddlewareIdentityProvider/Pages/Index.cshtml.cs
using ComponentSpace.Saml2.Middleware;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Text;

namespace MiddlewareIdentityProvider.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public IActionResult OnGetInitiateSingleSignOn()
        {
            // Pass control to the SAML middleware for IdP-initiated SSO.
            var url = SamlMiddlewareDefaults.InitiateSingleSignOnPath;

            if (!string.IsNullOrEmpty(Request.PathBase))
            {
                var stringBuilder = new StringBuilder();

                stringBuilder.Append(Request.PathBase);
                stringBuilder.Append(url);

                url = stringBuilder.ToString();
            }

            return LocalRedirect(url);
        }
    }
}

SSO/MiddlewareIdentityProvider/Pages/About.cshtml
@page
@model MiddlewareIdentityProvider.Pages.AboutModel
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

<p>
    This example demonstrates using the ComponentSpace SAML v2.0 library's middleware to enable SAML single sign-on
    as the identity provider.
</p>
<p>
    It includes support for identity provider (IdP) and service provider (SP) initiated
    single sign-on (SSO) and single logout (SLO).
</p>
<h4>Product Information</h4>
<p>
    @Model.ProductInformation
</p>
<p>
    This is <environment exclude="Development">not</environment> a development environment.
</p>

SSO/MiddlewareIdentityProvider/Pages/Contact.cshtml
@page
@model MiddlewareIdentityProvider.Pages.ContactModel
@{
    ViewData["Title"] = "Contact";
}

<h1>Contact</h1>

<p>If you need assistance, please feel free to contact us by email or on our <a href="https://www.componentspace.com/forums" target="_blank">online forums</a>.</p>

<address>
    <strong>Support:</strong> <a href="mailto:support@componentspace.com">support@componentspace.com</a><br />
    <strong>Sales:</strong> <a href="mailto:sales@componentspace.com">sales@componentspace.com</a>
</address>

SSO/MiddlewareIdentityProvider/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div class="jumbotron">
    <h1 class="display-4">Middleware Identity Provider</h1>
    <p class="lead">
        This example demonstrates using the ComponentSpace SAML v2.0 library's middleware to enable SAML single sign-on
        as the identity provider.
    </p>
    <p><a asp-page-handler="InitiateSingleSignOn" class="btn btn-primary btn-lg">SSO to the Service Provider</a></p>
</div>